 version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - cluster.name=iszheltov
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.12.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  logstash:
    image: logstash:8.12.2
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    volumes:
      - ./logs:/var/log/nginx
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    ports:
      - "80:80"

  filebeat:
     image: elastic/filebeat:8.12.2
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/var/log/nginx
    depends_on:
      - elasticsearch
    command: filebeat -e -strict.perms=false


volumes:
  esdata:
    driver: local